import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        {/* Sticky Navbar */}
        <Navbar className="sticky top-0 z-50" />
        {/* Main content fills available space */}
        <main className="flex-1 container px-6">{children}</main>
        {/* Footer always at bottom */}
        <Footer />
      </body>
    </html>
  );
}
