import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import QueryProvider from "../providers/QueryProvider";
import { CartProvider } from "../context/CartContext";
import { WishlistProvider } from "../context/WishlistContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen `}>
        <QueryProvider>
          <WishlistProvider>
            <CartProvider>
            {/* Sticky Navbar */}
            <Navbar className="sticky top-0 z-50 mx-auto" />
            {/* Main content fills available space */}
            <main className="flex-1 pt-4">{children}</main>
            {/* Footer always at bottom */}
            <Footer />
          </CartProvider>
          </WishlistProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
